name: Gugercin MSD Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:    
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@v1
      with:
          version: '1.6.2'
    - uses: julia-actions/julia-buildpkg@master
    - run: julia --project system_pipelines/create_gugercin_models.jl
    - uses: actions/upload-artifact@v2
      with:
        name: GugercinN100Mat
        path: GugercinN100.mat
    - uses: actions/upload-artifact@v2
      with:
        name: GugercinN1000Mat
        path: GugercinN1000.mat
    - uses: actions/upload-artifact@v2
      with:
        name: GugercinN20000Mat
        path: GugercinN20000.mat
    - uses: actions/upload-artifact@v2
      with:
        name: AllModelsMat
        path: GugercinN*.mat
    - uses: actions/upload-artifact@v2
      with:
        name: GugercinN100H5
        path: GugercinN100.h5
    - uses: actions/upload-artifact@v2
      with:
        name: GugercinN1000H5
        path: GugercinN1000.h5
    - uses: actions/upload-artifact@v2
      with:
        name: GugercinN20000H5
        path: GugercinN20000.h5
    - uses: actions/upload-artifact@v2
      with:
        name: AllModelsH5
        path: GugercinN*.h5
