name: Poro Model Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:    
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@v1
      with:
          version: '1.6.2'
    - uses: julia-actions/julia-buildpkg@master
    - run: julia --project system_pipelines/create_poro_models.jl
    - uses: actions/upload-artifact@v2
      with:
        name: PoroModelN320Mat
        path: PoroModelN320.mat
    - uses: actions/upload-artifact@v2
      with:
        name: PoroModelN980Mat
        path: PoroModelN980.mat
    - uses: actions/upload-artifact@v2
      with:
        name: PoroModelN1805Mat
        path: PoroModelN1805.mat
    - uses: actions/upload-artifact@v2
      with:
        name: PoroModelAllMat
        path: PoroModelN*.mat
    - uses: actions/upload-artifact@v2
      with:
        name: PoroModelN320H5
        path: PoroModelN320.h5
    - uses: actions/upload-artifact@v2
      with:
        name: PoroModelN980H5
        path: PoroModelN980.h5
    - uses: actions/upload-artifact@v2
      with:
        name: PoroModelN1805H5
        path: PoroModelN1805.h5
    - uses: actions/upload-artifact@v2
      with:
        name: PoroModelAllH5
        path: PoroModelN*.h5
